version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '07:00'
      timezone: 'Europe/Zurich'
    labels: ['dependencies', 'npm']
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        applies-to: 'version-updates'
        update-types: ['minor', 'patch']
        patterns: ['*']
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '07:15'
      timezone: 'Europe/Zurich'
    labels: ['dependencies', 'github-actions']
